export enum PROVINCES {
    EASTERN_CAPE = "EASTERN_CAPE",
    FREE_STATE = "FREE_STATE",
    GAUTENG = "GAUTENG",
    KWAZULU_NATAL = "KWAZULU_NATAL",
    LIMPOPO = "LIMPOPO",
    MPUMALANGA = "MPUMALANGA",
    NORTHERN_CAPE = "NORTHERN_CAPE",
    NORTH_WEST = "NORTH_WEST",
    WESTERN_CAPE = "WESTERN_CAPE",
}
