name: build

on: 
  push: 
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: npm install, and build
        run: |
          yarn install --legacy-peer-deps
          npm run build --if-present
