name: build

on: 
  push: 
    branches: [ main, develop/** ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: npm install, and build
        run: |
          npm install
          npm run build --if-present
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: prod-whatsamenu-client
          path: dist
          retention-days: 1
      - uses: actions/download-artifact@v3
        with:
          name: prod-whatsamenu-client
          path: dist
      - name: Display structure of downloaded files
        run: ls -R
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          source: "dist/"
          target: "~/apps/whatsamenu-client"
